export const AGRAELUS_WIN_TEXTS = [
  'AGRA W', 'CHAT L', 'AGRA SWEEP', 'STREAMER DIFF', 'ABSOLUTE CINEMA',
  'CHAT IN SHAMBLES', 'EZ', 'THE KING HAS ARRIVED', 'RIGGED FOR CONTENT',
  'CHAT FELL OFF', 'BRAIN OF STREAMER', 'CHAT COOKED', 'GG CHAT',
  'AGRA DIFF', 'FREE REAL ESTATE', 'CHAT NEVER RECOVERS', 'MONKEY GOD',
  'CRACKED', 'CHAT ratio\'d', 'THAT\'S GAME',
];

export const CHATTER_WIN_TEXTS = [
  'CHAT W', 'AGRA L', 'CHAT DIFF', 'THE HIVEMIND WINS', 'MODS???',
  'LULW', 'ABSOLUTE CHATTER', 'WE TAKE THOSE', 'GET REKT', 'RIGGED',
  'CHAT CARRIED', 'MID STREAMER', 'CHAT GOATED', 'FREE WIN',
  'CHAT UNITED', 'THE COLLECTIVE WINS', '1000 IQ CHAT', 'GGWP AGRA',
  'CHAT DID THAT', 'HIVEMIND DIFF',
];

export const AGRAELUS_LOSE_TEXTS = [
  'AGRA L', 'CHAT DIFF', 'MODS???', 'LULW', 'RIGGED', 'BRUH',
  'AGRA COOKED', 'THAT\'S CRAZY', 'NO SHOT', 'AGRA IN SHAMBLES',
  'GET FUCKED', 'F IN CHAT', 'AGRA RATIO\'D', 'DOWN BAD',
  'CHAT WON THIS ONE', 'AGRA FELL OFF', 'REFUND', 'IT\'S OVER',
  'CHAT DIFF FR', 'SKILL ISSUE',
];

export const CHATTER_LOSE_TEXTS = [
  'CHAT L', 'AGRA DIFF', 'RIGGED', 'NOOOOO', 'REFUND', 'MODS', 'FRAUD',
  'SCAM', 'CHAT LOST', 'CHAT IN SHAMBLES', 'HIVEMIND FAILED',
  'CHAT COOKED', 'F IN CHAT', 'AGRA COOKS AGAIN', 'CHAT RATIO\'D',
  'IT\'S OVER FOR CHAT', 'DOWN HORRENDOUS', 'CHAT DIFF (BAD)',
  'MID CHAT', 'SKILL ISSUE CHAT',
];

export const NEAR_MISS_TEXTS = [
  'NO WAY', 'WAIT', 'HOLD', "AIN'T NO WAY", 'SURELY', 'BRO', '...',
  'NAH', 'HOLD ON', 'WAIT WAIT WAIT',
];

export const CHAT_SPAM_WIN = [
  'W', 'LULW', 'EZ', 'RIGGED', 'OMEGALUL', 'NO SHOT', 'WE WON',
  'CHAT DIFF', 'AGRA L', 'LMAO', 'MODS???', 'GGWP',
];

export const CHAT_SPAM_LOSE = [
  'L', 'RIGGED', 'NOOOOO', 'REFUND', 'MODS', 'FRAUD', 'SCAM',
  'CHAT LOST', 'BRUH', 'ITS OVER',
];

export function randomOf(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
