export const AGRAELUS_WIN_TEXTS = [
  'AGRA W', 'CHAT L', 'AGRA SWEEP', 'STREAMER DIFF', 'ABSOLUTE CINEMA',
  'CHAT JE V KONCÍCH', 'EZ', 'KRÁL DORAZIL', 'RIGGED PRO CONTENT',
  'CHAT ODPADL', 'MOZEK STREAMERA', 'CHAT UVAŘEN', 'GG CHAT',
  'AGRA DIFF', 'ZADARMO', 'CHAT SE Z TOHO NEVZPAMATUJE', 'OPICE VYHRÁLA',
  'CRACKED', 'CHAT RATIO', 'TO JE GAME',
];

export const CHATTER_WIN_TEXTS = [
  'CHAT W', 'AGRA L', 'CHAT DIFF', 'HIVEMIND VYHRÁVÁ', 'MODS???',
  'LULW', 'ABSOLUTNÍ CHATTER', 'BEREME', 'GET REKT', 'RIGGED',
  'CHAT CARRY', 'MID STREAMER', 'CHAT GOATED', 'FREE WIN',
  'CHAT SPOJEN', 'KOLEKTIV VYHRÁVÁ', '1000 IQ CHAT', 'GGWP AGRA',
  'CHAT TO UDĚLAL', 'HIVEMIND DIFF',
];

export const AGRAELUS_LOSE_TEXTS = [
  'AGRA L', 'CHAT DIFF', 'MODS???', 'LULW', 'RIGGED', 'BRUH',
  'AGRA UVAŘEN', 'TO JE ŠÍLENÝ', 'ANI NÁHODOU', 'AGRA V KONCÍCH',
  'F DO CHATU', 'AGRA RATIO', 'DOWN BAD', 'CHAT TO BERE',
  'AGRA ODPADL', 'REFUND', 'JE KONEC', 'SKILL ISSUE',
];

export const CHATTER_LOSE_TEXTS = [
  'CHAT L', 'AGRA DIFF', 'RIGGED', 'NEEEEE', 'REFUND', 'MODS', 'FRAUD',
  'SCAM', 'CHAT PROHRÁL', 'CHAT V KONCÍCH', 'HIVEMIND SELHAL',
  'CHAT UVAŘEN', 'F DO CHATU', 'AGRA VAŘÍ', 'CHAT RATIO',
  'JE KONEC PRO CHAT', 'MID CHAT', 'SKILL ISSUE CHAT',
];

export const NEAR_MISS_TEXTS = [
  'NEKECEJ', 'POČKEJ', 'DRŽ', 'ANI NÁHODOU', 'URČITĚ', 'BRO', '...',
  'NAH', 'POČKAT', 'POČKEJ POČKEJ',
];

export const CHAT_SPAM_WIN = [
  'W', 'LULW', 'EZ', 'RIGGED', 'OMEGALUL', 'ANI NÁHODOU', 'VYHRÁLI JSME',
  'CHAT DIFF', 'AGRA L', 'LMAO', 'MODS???', 'GGWP',
];

export const CHAT_SPAM_LOSE = [
  'L', 'RIGGED', 'NEEEEE', 'REFUND', 'MODS', 'FRAUD', 'SCAM',
  'CHAT PROHRÁL', 'BRUH', 'JE KONEC',
];

export function randomOf(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
